# Generated by Django 5.2.5 on 2025-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
